name: Update Dockerfile

on:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  main:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Install pip requirements
      run: pip install -r requirements.txt
    - name: Run updater script
      run: python3 updater.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
