name: Update Dockerfile

on:
  schedule:
    - cron:  '0 12 * * *'

jobs:
  main:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        ref: master
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    #- name: Install setuptools
    #  run: sudo apt install python3-setuptools
    - name: Install pip requirements
      run: pip3 install -r requirements.txt
    - name: Run updater script
      run: python3 updater.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
