name: Test and Lint

on:
  pull_request:
    paths:
    - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build .

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint
      uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error