name: Build and Lint

on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/test.yml

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEBTREES_VERSION: "2.1.18"

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: python dev/build_test_version.py --webtrees_version $WEBTREES_VERSION

  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: info
          ignore: DL3008
