name: Test

on: pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Lint
      uses: luke142367/Docker-Lint-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET: Dockerfile
    - name: Build
      run: docker build .