name: Update Dockerfile

on:
  schedule:
    - cron:  '0 12 * * *'
  repository_dispatch:

jobs:
  main:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        ref: master

    - name: Cache Pip
      uses: actions/cache@v2
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('**/requirements.txt') }}

    - name: Update apt
      run: sudo apt update

    - name: Setup Python 3.8
      uses: actions/setup-python@v2.0.1
      with:
        python-version: 3.8

    - name: Install pip Requirements
      run: pip3 install -r requirements.txt

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3.1.0
      with:
        buildx-version: latest
        qemu-version: latest
        skip-cache: false

    - name: Cache Docker Layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: buildx

    - name: Docker Login
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io

    - name: Create Builder
      run: docker buildx create --use --name build --node build --driver-opt network=host

    - name: Run Updater Script
      run: python3 updater.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #BUILDX_PLATFORMS: ${{ steps.buildx.outputs.platforms }}
