name: Check and Push Updates

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs:
      forced:
        type: string
        required: false
        description: "Space-seperated version numbers to force update of"

jobs:
  get-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install Requirements
        run: |
          python -m pip install pip wheel --upgrade
          python -m pip install -r dev/requirements.txt

      - name: Get Versions
        id: script
        run: python3 dev/versionchecker.py --forced ${{ inputs.forced }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

    outputs:
      matrixes: ${{ steps.script.outputs.matrixes }}

  build-versions:
    needs: get-versions
    if: ${{ fromJSON(needs.get-versions.outputs.matrixes.builder).include[0] != null }}
    strategy:
      matrix: ${{ fromJSON(needs.get-versions.outputs.matrixes.builder) }}

    permissions:
      contents: read
      packages: write

    uses: NathanVaughn/reusable-actions/.github/workflows/docker-build-push.yml@main
    with:
      platform: ${{ matrix.platform }}
      tags: ${{ matrix.tags }}
      context: docker
      dockerfile: docker/Dockerfile
      buildargs: |
        WEBTREES_VERSION=${{ matrix.webtrees_version }}
        PHP_VERSION=${{ matrix.php_version }}
        PATCH_VERSION=${{ matrix.patch_version }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  create-releases:
    needs:
      - get-versions
      - build-versions
    if: ${{ fromJSON(needs.get-versions.outputs.matrixes.builder).include[0] != null }}

    strategy:
      matrix: ${{ fromJSON(needs.get-versions.outputs.matrixes.releaser) }}

    permissions:
      contents: write

    uses: NathanVaughn/reusable-actions/.github/workflows/create-release.yml@main
    with:
      tag: ${{ matrix.tag }}
      body: ${{ matrix.body }}
      prerelease: ${{ matrix.prerelease }}
